name: salter 

channels:
    - astropy

dependencies:
    - astropy
    - scipy
    - Cython
    - matplotlib
    - numpy
    - h5py
    - astroquery
    - pip:
        - batman-package
        - kplr
